# config for Random Chests

# time to delay first item spawn (default is 10 ticks)
delayTime: 10

# time between each spawn (default is 2400 ticks)
spawnTime: 2400

# set to true if you want only one spawned chest on the map at a time
unspawnPreviousChest: false

# items that chests can spawn (use names, not ID numbers)
allowedItems:
  - cauldron
  - saddle
  - cocoa

# nae of the world where you will spawn chests
world: world