# config for Random Chests

# time to delay first item spawn (default is 10 ticks)
delayTime: 10

# time between each spawn (default is 2400 ticks)
spawnTime: 2400

# set to true if you want only one spawned chest on the map at a time (default: true)
unspawnPreviousChest: true


# items that chests can spawn (use names, not ID numbers)
allowedItems:
  - diamond
  - dirt
  - stone

# number of item slots per spawned chest (default is 3)
numItems: 3

# name of the world where you will spawn chests (the folder name)
world: world

# spawn range extrema (default: X: -25000 - 25000, Z: -25000 - 25000)
minX: -25000
maxX: 25000
minZ: -25000
maxZ: 25000