name: LuckyChests
main: com.drewhiggins.bukkit.LuckyChests.LuckyChests
version: 0.0.1

commands:
  lc spawn:
    description: Forces the spawn of a new chest
    usage: /lc spawn
    permission: luckychest.spawn
    permission-message: You don't have permission to do that.